In [2]:
import pandas as pd


In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [5]:
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [6]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [7]:
# What's the version of Pandas that you installed?
pd.__version__

'2.2.3'

In [8]:
#How many records are in the dataset?
#ANS = 2160

In [10]:
#Records count
#How many records are in the dataset?

#12
#1000
#2160
#12160

len(df)

2160

In [11]:
#Laptop brands
#How many laptop brands are presented in the dataset?

#12
#27
#28
#2160
#ANS: To display number of unique values use: df.Brand.nunique()

In [14]:
df.Brand.unique()

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [15]:
df.Brand.nunique()

27

Q4. Missing values
# Number of columns with missing values
len(
    df.isnull().sum()[
    df.isnull().sum() != 0
    ]
)

In [16]:
len( df.isnull().sum()[ df.isnull().sum() != 0 ] )

3

In [20]:
df.isnull().sum() != 0

Laptop          False
Status          False
Brand           False
Model           False
CPU             False
RAM             False
Storage         False
Storage type     True
GPU              True
Screen           True
Touch           False
Final Price     False
dtype: bool

Q5. Maximum final price

In [19]:
# Maximum final price of Dell notebooks
df[df["Brand"] == "Dell"]["Final Price"].max()

np.float64(3936.0)

Q6. Median value of Screen
Let's find the median value of Screen column in the dataset:

In [21]:
# median of screen sizes
df.Screen.median()

np.float64(15.6)

Next, we can calculate the most frequent value of the same Screen column:

In [23]:
df.Screen.mode()

0    15.6
Name: Screen, dtype: float64

Let's use fillna method to fill the missing values in Screen column with the most frequent value from the previous step:

In [24]:
# fill missing values
df["Screen"] = df.Screen.fillna(df.Screen.mode().loc[0])

# Check if there is still missing values in `Screen` column
df.Screen.isnull().sum()

np.int64(0)

Now, we calculate the median value of Screen once again:

In [25]:
# new median of Screen size
df.Screen.median()

np.float64(15.6)

No it has not changed

Sum of weights
We select all the "Innjoo" laptops from the dataset:

In [26]:
# Dataset of Innjoo Laptops
df_Injoo = df[df.Brand == "Innjoo"]

# Visualize
df_Injoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

2. We select only columns RAM, Storage, Screen:

In [27]:
# Subset of data
df_Injoo_subset = df_Injoo[["RAM", "Storage", "Screen"]]

# result
df_Injoo_subset

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

We create X, the underlying NumPy array:


In [28]:
# import numpy package
import numpy as np

# Create array of data
X = np.array(df_Injoo_subset)
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

4. We compute matrix-matrix multiplication between the transpose of X and X and call it XTX:

In [29]:
# Compute matrix-matrix multiplication
XTX = X.T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

5. The inverse of XTX:

In [30]:
# Inverse of the matrix `XTX`
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

6. We now create an array y with values [1100, 1300, 800, 900, 1000, 1100]:

In [31]:
# Create an array
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

8.The sum of all the elements of the result is given by:

In [34]:
# Sum of all elements
w.sum()

NameError: name 'w' is not defined